### ISSUE TITLE
Questions on Base Model and Head Sparsification

### ISSUE THREAD

**Issue by Oldify** [OpenSparseLLMs/LLaMA-MoE-v2#1]
1. What are the specific (technical) reasons or differences for choosing instructed LLMs as base models, especially in comparison to your previous excellent work llama-moe?
2. Attention heads can be effectively sparsified by carefully managing their KV cache. Preserving the KV cache for each head can significantly reduce the performance gap between sparsified and dense models. For more details, you can refer to [Section 3.2.2 of the paper](https://arxiv.org/pdf/2405.09274).

Thank you guys for your super interesting work!

**Comment by XiaoYee** [comment]
1.

**Comment by XiaoYee** [comment]
1. To construct an instructed MoE, we take the first step in splitting the instructed LLM and applying post-training. This approach is both more intuitive and cost-efficient, and it allows us to assess a wider range of capabilities, including code and math. We will also provide updates on the results of splitting the base model and post-training in the coming days. Thank you for your attention.

2. We will refer to this paper. Thanks for your recommendation.
